# Generated by Django 3.2.9 on 2021-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_id', models.CharField(max_length=64, null=True, unique=True, verbose_name='ID собеседника')),
                ('companion_name', models.CharField(max_length=64, null=True, verbose_name='Имя собеседника')),
            ],
            options={
                'verbose_name_plural': 'Собеседники',
                'ordering': ('companion_id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, null=True, verbose_name='ID пользователя')),
                ('msg_text', models.CharField(max_length=64, null=True, verbose_name='Текст сообщения')),
                ('msg_time', models.CharField(max_length=64, null=True, verbose_name='Время отправки')),
                ('companion_id', models.CharField(max_length=64, null=True, unique=True, verbose_name='ID собеседника')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'ordering': ('companion_id',),
            },
        ),
    ]
