# Generated by Django 3.2.9 on 2021-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='companion_id',
            field=models.CharField(max_length=64, null=True, verbose_name='ID собеседника'),
        ),
    ]
